const productosLimpieza = [
  {
    id: 1,
    img: "https://m.media-amazon.com/images/I/71Y48ncUWYL._AC_UL320_.jpg",
    nombre: "Detergente líquido",
    categoria: "Limpieza del hogar",
    cantidad: 50,
    precio: 5.99,
  },
  {
    id: 2,
    img: "https://m.media-amazon.com/images/I/71ZmMPJ5JyL._AC_UL320_.jpg",
    nombre: "Limpiavidrios",
    categoria: "Limpieza del hogar",
    cantidad: 30,
    precio: 3.49,
  },
  {
    id: 3,
    img: "https://m.media-amazon.com/images/I/51lzJxNJdwL._AC_UL320_.jpg",
    nombre: "Desinfectante multiusos",
    categoria: "Limpieza del hogar",
    cantidad: 40,
    precio: 4.99,
  },
  {
    id: 4,
    img: "https://m.media-amazon.com/images/I/61H2E0ykIYL._AC_UL320_.jpg",
    nombre: "Quitamanchas en spray",
    categoria: "Lavandería",
    cantidad: 25,
    precio: 6.99,
  },
  {
    id: 5,
    img: "https://m.media-amazon.com/images/I/61zRF280nPL._AC_UL320_.jpg",
    nombre: "Desengrasante industrial",
    categoria: "Limpieza industrial",
    cantidad: 20,
    precio: 9.99,
  },
  {
    id: 6,
    img: "https://m.media-amazon.com/images/I/61BkXCTl28L._AC_UL320_.jpg",
    nombre: "Jabón en polvo",
    categoria: "Lavandería",
    cantidad: 35,
    precio: 7.49,
  },
  {
    id: 7,
    img: "https://m.media-amazon.com/images/I/61xKVrivp2L._AC_UL320_.jpg",
    nombre: "Desodorante de ambientes",
    categoria: "Ambientadores",
    cantidad: 50,
    precio: 3.99,
  },
  {
    id: 8,
    img: "https://m.media-amazon.com/images/I/61S0ov3rY8L._AC_UL320_.jpg",
    nombre: "Esponjas de limpieza",
    categoria: "Accesorios de limpieza",
    cantidad: 100,
    precio: 1.99,
  },
  {
    id: 9,
    img: "https://m.media-amazon.com/images/I/31YgJsNVitL._AC_UL320_.jpg",
    nombre: "Cepillo para baño",
    categoria: "Accesorios de limpieza",
    cantidad: 80,
    precio: 2.49,
  },
];

export default productosLimpieza;
